const quizQuestions = [
    {
        index : 1,
        question : "What is the Capital of Pakistan?",
        optiona : "Islamabad",
        optionb : "Lahore",
        optionc : "Karachi",
        optiond : "Peshawar",
        correctAnswer : "Islamabad",
    },
    {
        index : 2,
        question : "What is the Capital of Punjab?",
        optiona : "Islamabad",
        optionb : "Lahore",
        optionc : "Karachi",
        optiond : "Peshawar",
        correctAnswer : "Lahore",
    },
    {
        index : 3,
        question : "What is the Capital of KPK?",
        optiona : "Islamabad",
        optionb : "Lahore",
        optionc : "Karachi",
        optiond : "Peshawar",
        correctAnswer : "Peshawar",
    },
    {
        
        index : 4,
        question : "What is the Capital of Sindh?",
        optiona : "Islamabad",
        optionb : "Lahore",
        optionc : "Karachi",
        optiond : "Peshawar",
        correctAnswer : "Karachi",
    },
    {
        index : 5,
        question : "What is the Capital of Balochistan?",
        optiona : "Islamabad",
        optionb : "Quetta",
        optionc : "Karachi",
        optiond : "Peshawar",
        correctAnswer : "Quetta",
    },
]
